tags:
  - tag: Action_Object
    type: TypeReference
    referenceKind: xmlObject
    referenceType: GameObjectType
  - tag: Action_Target
    type: TypeReference
    referenceKind: xmlObject
    referenceType: GameObjectType
  - tag: Action_Relevance_Type
    type: DynamicEnumValue
    referenceKind: enum
    enumName: ActionRelevanceType
  - tag: Action_Relevance_Constant
    type: Float
  - tag: Action_Distance_From_Target_Curve
    type: IntFloatTupleList
  - tag: Action_Health_Percentage_Curve
    type: IntFloatTupleList
