name: AIGoalApplicationTarget
kind: schemaFixed
isBitfield: true
description:
  en: "Bitfield describing which entity types an AI goal can be applied to."
values:
  - name: FRIENDLY
  - name: FRIENDLY_UNIT
  - name: FRIENDLY_STRUCTURE
  - name: FRIENDLY_BUILD_PAD
  - name: FRIENDLY_REINFORCEMENT_POINT
  - name: ENEMY
  - name: ENEMY_UNIT
  - name: ENEMY_STRUCTURE
  - name: ENEMY_BUILD_PAD
  - name: ENEMY_REINFORCEMENT_POINT
  - name: NEUTRAL
  - name: GLOBAL
  - name: TACTICAL_LOCATION
